// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxndwvmdngmqjcgszxce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4bmR3dm1kbmdtcWpjZ3N6eGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzQyNjAsImV4cCI6MjA2MTI1MDI2MH0.7E84DuGOQS1k3zTrkzEpCrQflMhLlGPp7kifSUa_LAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);